Pages/3D-Visualizations/index.html, Pages/About-Us/index.html, Pages/Doubt Engine/index.html, Pages/Quizes/index.html, Pages/Simulation/index.html, Pages/Videos/index.html, index.html, style.css
- Added home button in nav bar.
- Fixed CSS in nav bar after adding the button.
**Kindly merge this PR under SWOC or let me know for any further changes needed to be made related to it. Thankyou!**
=> added home button to nav bar

Pages/3D-Visualizations/style.css, Pages/Quizes/style.css, Pages/Simulation/style.css, Pages/Videos/style.css
Closes #15 
cursor changes to pointer while hovering on interact button, also added a little transition animation to smoothen the effect
=> pointer cursor on interact button hover

index.html, style.css
=> Check of doubt engine changed to green

Components/Simulations/OrbitalConfiguration-Simulator/styles.css, Components/Simulations/Waves-Simulator/styles.css, Pages/3D-Visualizations/sources/button-1/style.css, Pages/3D-Visualizations/sources/button-2/style.css, Pages/3D-Visualizations/sources/button-3/style.css, Pages/3D-Visualizations/sources/button-4/style.css, Pages/3D-Visualizations/style.css, Pages/About-Us/style.css, Pages/Doubt Engine/style.css, Pages/Quizes/style.css, Pages/Quizes/tests/button-1/style.css, Pages/Quizes/tests/button-2/style.css, Pages/Quizes/tests/button-3/style.css, Pages/Quizes/tests/button-4/style.css, Pages/Simulation/Components/Simulations/OrbitalConfiguration-Simulator/styles.css, Pages/Simulation/Components/Simulations/Waves-Simulator/styles.css, Pages/Simulation/Interactions/Button-1/style.css, Pages/Simulation/Interactions/Button-2/style.css, Pages/Simulation/Interactions/Button-3/style.css, Pages/Simulation/Interactions/Button-4/style.css, Pages/Simulation/style.css, Pages/Videos/sources/button-1/style.css, Pages/Videos/sources/button-2/style.css, Pages/Videos/sources/button-3/style.css, Pages/Videos/sources/button-4/style.css, Pages/Videos/style.css, style.css
Closes #18
I Have added a better scrollbar for better user experience. also, I apologize for the branch name bymistakely i have named it "fix/NAVBAR" although it has nothing to do with navbar.  
|  Original  | 
| Updated   |
=> added better scrollbar 

Pages/Doubt Engine/style.css
Closes #47 
Added hover effect on the 'Get Answers' button in the Doubt Engine Section. Hover effect includes changing the cursor to pointer and so on.
https://github.com/JAYESHBATRA/Virtuo-Learn/assets/103977344/99467f7e-1601-47f8-b98f-474b15ce66b0
https://github.com/JAYESHBATRA/Virtuo-Learn/assets/103977344/fd14e96b-c5b5-4c4e-a3b2-1f378fc69540
=> Feat: Added a hover effect on the 'Get Answers' button

Pages/About-Us/index.html, Pages/About-Us/media-queries.css, Pages/About-Us/style.css, index.html, media-queries.css, style.css
Closes #50 
I have updated the About Page into Tailwind CSS. I could not move all the media queries into it because having every little customization in the tailwind CSS is not feasible. I have cleaned the Style.css file. Please review the changes and let me know if any update is required.
Also, I have added comments to the Style.css for the required components.
And the conflict is merged.
And refactored the home page navbar issue.
=> Css to tailwind

Components/Simulations/OrbitalConfiguration-Simulator/index.html, Components/Simulations/Waves-Simulator/wave.html, Pages/3D-Visualizations/index.html, Pages/3D-Visualizations/sources/button-1/index.html, Pages/3D-Visualizations/sources/button-2/index.html, Pages/3D-Visualizations/sources/button-3/index.html, Pages/3D-Visualizations/sources/button-4/index.html, Pages/3D-Visualizations/sources/button-5/index.html, Pages/About-Us/index.html, Pages/Doubt Engine/index.html, Pages/Quizes/index.html, Pages/Quizes/tests/button-1/index.html, Pages/Quizes/tests/button-2/index.html, Pages/Quizes/tests/button-3/index.html, Pages/Quizes/tests/button-4/index.html, Pages/Quizes/tests/button-5/index.html, Pages/Quizes/tests/button-6/index.html, Pages/Simulation/Interactions/Button-1/index.html, Pages/Simulation/Interactions/Button-2/index.html, Pages/Simulation/Interactions/Button-3/index.html, Pages/Simulation/Interactions/Button-4/index.html, Pages/Simulation/index.html, Pages/Videos/index.html, Pages/Videos/sources/button-1/index.html, Pages/Videos/sources/button-2/index.html, Pages/Videos/sources/button-3/index.html, Pages/Videos/sources/button-4/index.html
Closes #17
Adde logo icon throughout every page
|      Original       |
|      Updated      |
=> fix rendering of icons

Pages/Quizes/tests/button-1/index.html, Pages/Quizes/tests/button-2/index.html, Pages/Quizes/tests/button-3/index.html, Pages/Quizes/tests/button-4/index.html, Pages/Quizes/tests/button-5/index.html, Pages/Quizes/tests/button-6/index.html
**Closes  #64** 
Addition of Home button in all Quiz Result Pages & Question Pages.
**## Description**
This PR adds a home page to all the quiz pages and the result pages. 
This helps the user to redirect easily to the home paage.
The improvements can be seen in the below screenshots: 
**Before making the changes :** 
**After making the improvements :**
=>  [Feature] Addition of Home button in all Quiz Result Pages & Question Pages.

index.html, media-queries.css, style.css
Closes #issue_number
#65
Fixed by removing the left styling from header-right and making some changes in hero-image class. the size was too small and the image was not centered.
|      Original       |
| original screenshot |
|     Updated       |
| updated screenshot |
=> Fixed hero-image #65

Pages/Doubt Engine/index.html, Pages/Doubt Engine/style.css
Closes #79 
I have updated the About Page into Tailwind CSS. I could not move all the media queries into it because having every little customization in the tailwind CSS is not feasible. I have cleaned the Style.css file. Please review the changes and let me know if any update is required.
=> Migrated Doubt Engine to Tailwind CSS

index.html, style.css
Closes #73 
I have added a "Scroll To Top" Button on the bottom right of the home page which will help the user to navigate to top of the page easily.
|      Original       |  
| ![image](https://github.com/JAYESHBATRA/Virtuo-Learn/assets/114342859/8bc9c89d-d5d8-4d81-b4b3-7321a1d95ba6) | 
|    Updated       |
| ![image](https://github.com/JAYESHBATRA/Virtuo-Learn/assets/114342859/b8e3dd7a-9826-4aa4-a484-92939f36e977) |
=> Added Scroll to Top On Home Page

CONTRIBUTION.md
Closes #issue_number
Fixes #81 
Added a CONTRIBUTION.md file for the repository
=> Added CONTRIBUTION.md file

Pages/3D-Visualizations/index.html, Pages/About-Us/index.html, Pages/Doubt Engine/index.html, Pages/Quizes/index.html, Pages/Simulation/index.html, Pages/Videos/index.html, scroll-reveal.js
Closes #23 
Added animation in all the pages in similar fashion as in home page to maintain homogeneity within the website.
=> animation in all the pages

Pages/3D-Visualizations/index.html, Pages/About-Us/index.html, Pages/Doubt Engine/index.html, Pages/Quizes/index.html, Pages/Simulation/index.html, Pages/Videos/index.html, index.html
Closes #85 
Alt texts for the images which were previously incorrect are now fixed.
=> Alt text in images are fixed.

style.css
Closes Issue #90 
The Navbar Items are not Showing perfectly on the Home Screen resolved that issue
=> Resolved the Bug of Navbar on Home Screen

style.css
Close Issue #97 
Fixed the Up arrow Button
=> Resolve the Error and Fixed the Up Arrow Button

Pages/Quizes/index.html
**Closes #82** 
**## Description**
This PR fixes the following :
- Alignment of Quizzes Subject-wise
- Mathematics , Physics, Chemistry, Biology.
- Improves interactivity for the user to choose subject-wise.
**## Screenshots**
The improvements before and after can be seen in the below attached screenshots:
**Before  :**  
**After :**
=> Alignment of Quizzes

Pages/Quizes/tests/button-1/script.js
#3
Closes #issue_number
Added the video links in the recommendation system 
https://github.com/JAYESHBATRA/Virtuo-Learn/assets/91714143/7c64daa6-620a-48e5-8ec9-8ff7ea4cc6c5
=> added the video links issue number #3

index.html
=> Added links

Pages/3D-Visualizations/index.html, Pages/3D-Visualizations/style.css, Pages/About-Us/index.html, Pages/About-Us/style.css, Pages/Doubt Engine/index.html, Pages/Doubt Engine/style.css, Pages/Quizes/index.html, Pages/Quizes/style.css, Pages/Simulation/index.html, Pages/Simulation/style.css, Pages/Videos/index.html, Pages/Videos/style.css, index.html, style.css
Closes #130 
This PR ensures :
- The current page status.
- Provides more clarity.
- Enhances the Nav Bar.
The screenshots before and after can be seen in the below attached photos : 
Before : 
After :
=> Enhancing Current Page in Nav-Bar

index.html, style.css
##Title #30 
Closes #30 
added whitespace between section big-feature and step 1 for consistent spacing
=> fix: Added white space between steps and features section.

Pages/Quizes/tests/button-1/script.js, Pages/Quizes/tests/button-1/solution.js, Pages/Quizes/tests/button-1/solutions.html, Pages/Quizes/tests/button-2/solution.html, Pages/Quizes/tests/button-2/solution.js, Pages/Quizes/tests/button-3/solution.html, Pages/Quizes/tests/button-3/solution.js, Pages/Quizes/tests/button-4/solution.html, Pages/Quizes/tests/button-4/solution.js, Pages/Quizes/tests/button-5/solution.html, Pages/Quizes/tests/button-5/solution.js, Pages/Quizes/tests/button-6/solution.html, Pages/Quizes/tests/button-6/solution.js, Pages/Quizes/tests/button-7/solution.html, Pages/Quizes/tests/button-7/solution.js, Pages/Quizes/tests/button-8/solution.html, Pages/Quizes/tests/button-8/solution.js
Issue number #4
Added  the solution page for every quiz
=> solution page added

style.css
Closes #162
Text is not looking odd anymore.
- [ x] My code adheres to the established style guidelines of the project.
- [ x] I have included comments in areas that may be difficult to understand.
- [ x] My changes have not introduced any new warnings.
- [x ] I have conducted a self-review of my code.
=> fix: Text alligned

Pages/Quizes/tests/button-9/index.html, Pages/Quizes/tests/button-9/style.css
Closes #150 
I have fixed the typo in Quizzes on the Sequence and series page and make footer visible.
=> fix: Fixed the typo and enhanced the UI

mode-switch.js
Closes #160 
Fixed the bug of dark mode toggling as when dark mode is switched and refreshing the page will load it as light mode. The bug is fixed using JavaScript local storage.
| https://www.loom.com/share/ec09993d139f45c6aa742d0f28ce58c0 | https://www.loom.com/share/aa9ca6f76c7b46e99c61a0a96097088f?sid=bc2dda4f-e6b7-4821-a347-12bfe46233da  |
| original video | updated video |
- [x ] My code adheres to the established style guidelines of the project.
- [ x] I have included comments in areas that may be difficult to understand.
- [x ] My changes have not introduced any new warnings.
- [ x] I have conducted a self-review of my code.
=> fix: Fixed Dark mode functionality Error 

Pages/Quizes/index.html, Pages/Quizes/style.css
Closes #164 
I have added arrow up functionality on the "Quizzes" Page.
=> feat: Added Up-Arrow button

Pages/3D-Visualizations/index.html, Pages/Quizes/index.html, Pages/Quizes/style.css, Pages/Simulation/index.html, Pages/Videos/index.html, Pages/Videos/style.css
Closes #179 
all icons are added on respective buttons
- [x ] My code adheres to the established style guidelines of the project.
- [x ] I have included comments in areas that may be difficult to understand.
- [x ] My changes have not introduced any new warnings.
- [ x] I have conducted a self-review of my code.
=> icon added on buttons

mode-switch.js, style.css
Closes #177 
Fixed hover effect for home button, if it is active
=> fix: fixed hover effect for home button

.hintrc, index.html, media-queries.css
=> [FIX] Fixed hover of Home Button background color

index.html
Reverts JAYESHBATRA/Virtuo-Learn#192
=> Revert "Issue No #183 [BUG FIXED] In social media section twitter logo is not showing."

Pages/3D-Visualizations/index.html, Pages/3D-Visualizations/style.css, Pages/About-Us/index.html, Pages/About-Us/style.css, Pages/Doubt Engine/index.html, Pages/Doubt Engine/style.css, Pages/Quizes/index.html, Pages/Quizes/style.css, Pages/Simulation/index.html, Pages/Simulation/style.css, Pages/Videos/index.html, Pages/Videos/style.css, index.html, style.css
Closes #190 
Hello !!
Since there wasn't a single navbar common to all ,I had to make changes in each HTML file required.
Due to short space between the elements after adding icons, the elements and icons where overlapping so I wrote some CSS to **fix it without affecting other CSS.**
=> Adding icons . #190

index.html, media-queries.css, style.css
fixed the responsiveness issue of footer
Closes #198 
The footer was previously not responsive, the useful links of the footer overflowed the container. Now the fix ensures that it is responsive under all screen widths.
|
| 
|
|
|
|
- [x ] My code adheres to the established style guidelines of the project.
- [x ] I have included comments in areas that may be difficult to understand.
- [x ] My changes have not introduced any new warnings.
- [x ] I have conducted a self-review of my code.
=> fix: footer ui fixes

Pages/Videos/sources/button-1/media-queries.css, Pages/Videos/sources/button-1/style.css, Pages/Videos/sources/button-2/media-queries.css, Pages/Videos/sources/button-3/media-queries.css, Pages/Videos/sources/button-4/media-queries.css
Closes #218 
Adding media queries for all four videos at max-width 1310px for correcting the footer position for mobile devices
| ![before](https://github.com/JAYESHBATRA/Virtuo-Learn/assets/98449874/1826dfe2-c947-45a6-8f94-63f98992ccf6) | ![now](https://github.com/JAYESHBATRA/Virtuo-Learn/assets/98449874/ffe05c9c-ca74-4897-b178-f6aab0bdcd83) |
=> fix: correcting footer position in mobile

Pages/Videos/sources/button-1/index.html, Pages/Videos/sources/button-1/style.css, Pages/Videos/sources/button-2/index.html, Pages/Videos/sources/button-2/style.css, Pages/Videos/sources/button-3/index.html, Pages/Videos/sources/button-3/style.css, Pages/Videos/sources/button-4/index.html, Pages/Videos/sources/button-4/style.css
Closes #223 
- Styling of the navbar in the video player section of the Videos section is now matched with the default styling of the navbar being used everywhere.
|      Original       |
| :-----------------: |
|      Updated       |
| :-----------------: |
=> fix: Navbar of the Video player section fixed.

Pages/3D-Visualizations/index.html, Pages/3D-Visualizations/media-queries.css, Pages/3D-Visualizations/style.css, Pages/About-Us/index.html, Pages/About-Us/media-queries.css, Pages/Doubt Engine/index.html, Pages/Doubt Engine/media-queries.css, Pages/Quizes/index.html, Pages/Quizes/media-queries.css, Pages/Quizes/style.css, Pages/Simulation/index.html, Pages/Simulation/media-queries.css, Pages/Simulation/style.css, Pages/Videos/index.html, Pages/Videos/media-queries.css, Pages/Videos/style.css, media-queries.css, style.css
All problems with navbar solved 
Fixes: #203 
https://github.com/JAYESHBATRA/Virtuo-Learn/assets/169196836/f8e6d16d-7b0b-4e46-9d86-3629c189d100
=> navbar made responsive

style.css
Previously the text is not properly Justified from both the end . This PR solves the justification of the text 
Closes #237 
I did some changes in style.css and updated the alignment of text to center  (text-align : center)  . 
| 
|
- [ x ] My code adheres to the established style guidelines of the project.
- [ x ] My changes have not introduced any new warnings.
- [ x ] I have conducted a self-review of my code.
=> feat: Justification Of text 

.vscode/settings.json, index.html, media-queries.css, mode-switch.js, style.css
The current dark/light mode toggle lacks animation, resulting in a sudden change in appearance that can be jarring for users.
Closes #266
The changes in this pull request focus on enhancing the user experience by adding animation to the dark/light mode toggle button. This animation provides visual feedback to users when they switch between dark and light modes. It improves the usability of the toggle switch and contributes to a smoother transition between modes, ultimately enhancing the overall user experience of the application.
|      Original       |     
| :-----------------: 
Updated       |
| :----------------: |
=> feat: Added animation to dark and light toggle

index.html, style.css
fixed issue #245
I have added a hovering effect for the icons and the headings  and made it interactive
=> feat: Added Hovering Effect  to Our Products Section

style.css
Closes #251 
I have removed the overflow issue of logo in nav bar of doubt engine page.
| ![Screenshot 2024-05-15 123724](https://github.com/JAYESHBATRA/Virtuo-Learn/assets/142597742/81f5745c-ee03-4d47-8cec-bc7ed0c03cce) | ![Screenshot 2024-05-16 195334](https://github.com/JAYESHBATRA/Virtuo-Learn/assets/142597742/dc498182-1815-44aa-b608-5eac983c9201)|
=> fix:  Made changes in size of logo

Pages/Quizes/tests/button-3/style.css
Before 
closes #284 
after the Improvement in UI , it enhances the interaction between user and our system.
I have only change the UI of respiration in plants yet, after receiving positive feedback from your side, i will proceed with remaining  sections.
=> Improved UI of Bio quiz section.

Pages/Simulation/Interactions/Button-2/sketch.js, Pages/Simulation/Interactions/Button-3/sketch.js
Closes #267 
The Bug was that every time the setup function and draw function ran it was creating new p tags.
=> fix: Performance Issue in Simulations

index.html
Closes #260
Added icons in Footer section
original
updated
=> Added icons in Footer section

Pages/About-Us/index.html, Pages/About-Us/style.css
Enhance 'About Us' Page with Hover and Sliding Effects 
fixed: #282
-->Before:
-->After:
Checklist
- ☑  My code adheres to the established style guidelines of the project.
- ☑ I have included comments in areas that may be difficult to understand.
- ☑ My changes have not introduced any new warnings.
- ☑ I have conducted a self-review of my code.
=> fix: About us Page hovering

style.css
Testimony area can be improved
Closes #321
Navbar's position was fixed for the whole website but Testimony flashcards are going over the navbar which is fixed.
|      Original       | 
| updated screenshot |
=> fix: Testimony Area UI

Pages/Quizes/tests/button-1/media-queries.css, Pages/Quizes/tests/button-1/style.css, Pages/Quizes/tests/button-2/media-queries.css, Pages/Quizes/tests/button-3/media-queries.css, Pages/Quizes/tests/button-4/media-queries.css, Pages/Quizes/tests/button-5/media-queries.css, Pages/Quizes/tests/button-5/style.css, Pages/Quizes/tests/button-6/media-queries.css, Pages/Quizes/tests/button-6/style.css, Pages/Quizes/tests/button-7/media-queries.css, Pages/Quizes/tests/button-8/media-queries.css, Pages/Quizes/tests/button-8/style.css, Pages/Quizes/tests/button-9/media-queries.css
improved chemistry Quiz section UI.
=> #306 UI improvement in chemistry quiz section. 

index.html
Closes : #310 
Enhanced the text and links in the product section to improve users experience.
before
after
=> feat: UI Enhanchement in products section 

CODE_OF_CONDUCT.md, LEARN.md, README.md
Fixes : #332 
- [ x] My code adheres to the established style guidelines of the project.
- [ x] I have included comments in areas that may be difficult to understand.
- [ x] My changes have not introduced any new warnings.
- [x ] I have conducted a self-review of my code.
Closes: #332
=> Fix: Adding necessary files - Code of Conduct  Learn.md and Enhanced Readme 

Pages/Quizes/tests/button-7/style.css, Pages/Quizes/tests/button-9/style.css
Reverts JAYESHBATRA/Virtuo-Learn#361
=> Revert "Maths quiz"

Pages/Quizes/tests/button-7/style.css, Pages/Quizes/tests/button-9/style.css
Reverts JAYESHBATRA/Virtuo-Learn#399
=> Revert "Revert "Maths quiz""

.github/workflows/auto-comment-on-pr-merge.yml
Closes #330 
I have added auto-comment-on-pr-merge.yml in .github/workflows directory. This file will add the feature of auto commenting when a pr is merged.
=> Auto commenting feature added for merged prs 

index.html, media-queries.css
Closes #324 
Made the footer section responsive.
| 
| 
https://github.com/JAYESHBATRA/Virtuo-Learn/assets/121669832/e893c878-199e-42c0-b03a-4c3ff2a85d3d
|
=> fix : Made footer responsive.

index.html, style.css
Closes #382
before
after
https://github.com/JAYESHBATRA/Virtuo-Learn/assets/137484958/4399e00c-fe6f-4a04-b679-ad6b6fee3f7a
=> feat : Added Heading and icons in Pricing box

.github/workflows/autocomment-iss-close.yml
Closes #341 
This feature aims to solve the problem of poor communication and lack of acknowledgment when issues are closed. By automatically commenting on closed issues, it ensures that contributors are informed about the closure and are thanked for their efforts. This helps maintain a positive and engaging community atmosphere, encouraging continued contributions and fostering good relationships between maintainers and contributors.
=> feat: added workflow as per issue #341
